baseURL = "https://chadballay.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
theme = "hugo-lithium-theme"
title = "Chad's Sandbox"
[[menu.main]]
name = "Impossible List"
url = "/impossible-list/"
weight = 5
[[menu.main]]
name = "Github"
url = "https://github.com/Chad-Ballay"
weight = 4
[[menu.main]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/chad-ballay/"
weight = 3
[[menu.main]]
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
name = "EDLPi"
url = "/EDLPi/"
weight = 1
[params]
description = "Ramblings of a misplaced man."
[params.logo]
alt = "Logo"
height = 50
url = "logo.png"
width = 50
[permalinks]
page = "/:title/"
post = "/:year/:month/:day/:title/"
