baseURL = "https://chadballay.com/"
languageCode = "en-us"
title = "Chad's Sandbox"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "EDLPi"
    url = "/EDLPi/"
    weight = 0
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/Chad_Ballay"
    weight = 3

[params]
    description = "Ramblings of a misplaced man."

[params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
